spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.104:8848
    gateway:
      routes:
        - id: admin_route
          uri: lb://gulimall-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
server:
  port: 88
